version: '3.8'
services:
  nginx:
    container_name: nginx
    ports:
      - "443:443"
    volumes:
    - wordpress:/var/www/html
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
    - wordpress
    networks:
      - my-netwok
    restart: on-failure
  wordpress:
    container_name: wordpress
    volumes:
    - wordpress:/var/www/wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - "9000"
    depends_on:
    - mariadb
    networks:
      - my-netwok
    restart: on-failure
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
    - mariadb:/var/lib/mysql
    networks:
      - my-netwok
    restart: unless-stopped
    expose:
      - "3306"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jusilanc/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jusilanc/data/mariadb'

networks:
  my-netwok:
    driver: bridge
